const INTERNAL_SERVER_ERROR = 500;
const INVALID_DATA_ERROR = 400;
const NO_DATA_WITH_ID_ERROR = 404;
const DUPLICATE_ERROR = 11000;
const INVALID_AUTHENTICATION = 401;

module.exports = {
  INTERNAL_SERVER_ERROR,
  INVALID_DATA_ERROR,
  NO_DATA_WITH_ID_ERROR,
  DUPLICATE_ERROR,
  INVALID_AUTHENTICATION,
};
