const INTERNAL_SERVER_ERROR = 500;
const INVALID_DATA_ERROR = 400;
const NO_DATA_WITH_ID_ERROR = 404;
const DUPLICATE_ERROR = 409;
const INVALID_AUTHENTICATION = 401;
const REFUSE_T0_AUTHORIZE_ERROR = 403;

module.exports = {
  INTERNAL_SERVER_ERROR,
  INVALID_DATA_ERROR,
  NO_DATA_WITH_ID_ERROR,
  DUPLICATE_ERROR,
  INVALID_AUTHENTICATION,
  REFUSE_T0_AUTHORIZE_ERROR,
};
